spring.application.name=Configuration GoTrip
server.port=8081

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/AppTemoin
spring.datasource.username=postgres
spring.datasource.password=Belouh
spring.datasource.driver-class-name=org.postgresql.Driver